### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by leafyelin** [zxbu/webdav-teambition#4]
在freebsd系统中（openjdk 1.7.0_261）运行出现错误：
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)`
请问是什么原因？

**Comment by leafyelin** [comment]
发现原因了，是openjdk版本太低，安装了openjkd8就好了
